name: apollak
favicon: null
layout_spectrum: 0.48923
typography_spectrum: 0.59482
title: apollak
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7653c9'
    - '#421d7a'
    - '#ff0008'
    - '#ffa962'
    - '#f7dbcf'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
